version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ml_postgres
    environment:
      POSTGRES_DB: ml_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ml_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: ml_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  ml-service:
    build: .
    container_name: ml_service_app
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=postgresql://admin:password@postgres:5432/ml_service
      - CHROMA_HOST=http://chroma:8000
    depends_on:
      - postgres
      - chroma

      
    volumes:
      - ./data:/app/data
      - ./src:/app/src 

volumes:
  postgres_data:
  chroma_data: